name: CI
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    ci:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [18.x]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: "Install modules"
              run: |
                  npm install
                  npx playwright install --with-deps chromium
            - name: Validate commit message
              run: npm run commitlint
            - name: Validate code style
              run: npm run lint
            - name: "Build project"
              run: npm run build
            - name: "Tests"
              run: npm run test:ci
